### ISSUE TITLE
Upgrading to Play 2.4.3 but not seeing the log entries

### ISSUE THREAD

**Issue by langley** [DrewEaster/realtime-search#5]
I'm in the middle of upgrading this app to Play 2.4.3 https://github.com/langley/realtime-search 
It all compiles and "runs" (after a fashion) now. The work is currently being done on the WIP branch of my fork. 

However, I don't see the logoutput. I've scattered some "debugging" printlns around in the actor code and can see them working, but the searches always return nothing. 

I'll be looking in to it, but any pointers would be most welcome! TIA!!!

**Comment by langley** [comment]
I have a version running in https://github.com/langley/realtime-search 
I'll do a pull request soon and hope to start the discussion about getting the typesafe template updated after that so others don't stumble into a non-working version.

**Comment by DrewEaster** [comment]
Hey - thanks for spotting this. I've not had much time to maintain this template recently so your contribution is very appreciated.

**Comment by langley** [comment]
Closed out an ancient issue.
